name: sam_2
channels:
  - anaconda
  - nvidia
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python==3.12.11
  - cuda==12.8.1
  - cudnn
  - pip==25.0
  - pip:
    - torch==2.5.1
    - torchvision>=0.20.1
    - numpy==2.3.0
    - tqdm==4.66.1
    - hydra-core==1.3.2
    - iopath==0.1.10
    - pillow==11.1.0

    # - matplotlib==3.10.0
    # - jupyter>=1.0.0
    - opencv-python==4.11.0.86

    # - black==24.2.0
    # - usort==1.0.2
    # - ufmt==2.0.0b2

    # # для примера из ноутбука Roboflow: https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/how-to-segment-images-with-sam-2.ipynb#scrollTo=UGv98ypgPA7c
    # - supervision
    # - jupyter_bbox_widget

